// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: meter.proto

package meter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeterIngestorService_SubmitReading_FullMethodName     = "/meter.MeterIngestorService/SubmitReading"
	MeterIngestorService_SubmitBatch_FullMethodName       = "/meter.MeterIngestorService/SubmitBatch"
	MeterIngestorService_StreamReadings_FullMethodName    = "/meter.MeterIngestorService/StreamReadings"
	MeterIngestorService_GetLatestReading_FullMethodName  = "/meter.MeterIngestorService/GetLatestReading"
	MeterIngestorService_GetReadingHistory_FullMethodName = "/meter.MeterIngestorService/GetReadingHistory"
)

// MeterIngestorServiceClient is the client API for MeterIngestorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeterIngestorServiceClient interface {
	// Submit a single meter reading (from field app or AMR gateway)
	SubmitReading(ctx context.Context, in *MeterReading, opts ...grpc.CallOption) (*MeterReadingResponse, error)
	// Submit a batch of readings (from AMR gateway bulk upload)
	SubmitBatch(ctx context.Context, in *BatchMeterReadings, opts ...grpc.CallOption) (*BatchMeterReadingResponse, error)
	// Streaming: AMR gateway streams readings in real time
	StreamReadings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MeterReading, BatchMeterReadingResponse], error)
	// Query latest reading for an account
	GetLatestReading(ctx context.Context, in *GetLatestReadingRequest, opts ...grpc.CallOption) (*MeterReading, error)
	// Query reading history for an account
	GetReadingHistory(ctx context.Context, in *GetReadingHistoryRequest, opts ...grpc.CallOption) (*ReadingHistoryResponse, error)
}

type meterIngestorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeterIngestorServiceClient(cc grpc.ClientConnInterface) MeterIngestorServiceClient {
	return &meterIngestorServiceClient{cc}
}

func (c *meterIngestorServiceClient) SubmitReading(ctx context.Context, in *MeterReading, opts ...grpc.CallOption) (*MeterReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeterReadingResponse)
	err := c.cc.Invoke(ctx, MeterIngestorService_SubmitReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meterIngestorServiceClient) SubmitBatch(ctx context.Context, in *BatchMeterReadings, opts ...grpc.CallOption) (*BatchMeterReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchMeterReadingResponse)
	err := c.cc.Invoke(ctx, MeterIngestorService_SubmitBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meterIngestorServiceClient) StreamReadings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MeterReading, BatchMeterReadingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeterIngestorService_ServiceDesc.Streams[0], MeterIngestorService_StreamReadings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MeterReading, BatchMeterReadingResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeterIngestorService_StreamReadingsClient = grpc.ClientStreamingClient[MeterReading, BatchMeterReadingResponse]

func (c *meterIngestorServiceClient) GetLatestReading(ctx context.Context, in *GetLatestReadingRequest, opts ...grpc.CallOption) (*MeterReading, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeterReading)
	err := c.cc.Invoke(ctx, MeterIngestorService_GetLatestReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meterIngestorServiceClient) GetReadingHistory(ctx context.Context, in *GetReadingHistoryRequest, opts ...grpc.CallOption) (*ReadingHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadingHistoryResponse)
	err := c.cc.Invoke(ctx, MeterIngestorService_GetReadingHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeterIngestorServiceServer is the server API for MeterIngestorService service.
// All implementations must embed UnimplementedMeterIngestorServiceServer
// for forward compatibility.
type MeterIngestorServiceServer interface {
	// Submit a single meter reading (from field app or AMR gateway)
	SubmitReading(context.Context, *MeterReading) (*MeterReadingResponse, error)
	// Submit a batch of readings (from AMR gateway bulk upload)
	SubmitBatch(context.Context, *BatchMeterReadings) (*BatchMeterReadingResponse, error)
	// Streaming: AMR gateway streams readings in real time
	StreamReadings(grpc.ClientStreamingServer[MeterReading, BatchMeterReadingResponse]) error
	// Query latest reading for an account
	GetLatestReading(context.Context, *GetLatestReadingRequest) (*MeterReading, error)
	// Query reading history for an account
	GetReadingHistory(context.Context, *GetReadingHistoryRequest) (*ReadingHistoryResponse, error)
	mustEmbedUnimplementedMeterIngestorServiceServer()
}

// UnimplementedMeterIngestorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeterIngestorServiceServer struct{}

func (UnimplementedMeterIngestorServiceServer) SubmitReading(context.Context, *MeterReading) (*MeterReadingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitReading not implemented")
}
func (UnimplementedMeterIngestorServiceServer) SubmitBatch(context.Context, *BatchMeterReadings) (*BatchMeterReadingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBatch not implemented")
}
func (UnimplementedMeterIngestorServiceServer) StreamReadings(grpc.ClientStreamingServer[MeterReading, BatchMeterReadingResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamReadings not implemented")
}
func (UnimplementedMeterIngestorServiceServer) GetLatestReading(context.Context, *GetLatestReadingRequest) (*MeterReading, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestReading not implemented")
}
func (UnimplementedMeterIngestorServiceServer) GetReadingHistory(context.Context, *GetReadingHistoryRequest) (*ReadingHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadingHistory not implemented")
}
func (UnimplementedMeterIngestorServiceServer) mustEmbedUnimplementedMeterIngestorServiceServer() {}
func (UnimplementedMeterIngestorServiceServer) testEmbeddedByValue()                              {}

// UnsafeMeterIngestorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeterIngestorServiceServer will
// result in compilation errors.
type UnsafeMeterIngestorServiceServer interface {
	mustEmbedUnimplementedMeterIngestorServiceServer()
}

func RegisterMeterIngestorServiceServer(s grpc.ServiceRegistrar, srv MeterIngestorServiceServer) {
	// If the following call panics, it indicates UnimplementedMeterIngestorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeterIngestorService_ServiceDesc, srv)
}

func _MeterIngestorService_SubmitReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeterReading)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeterIngestorServiceServer).SubmitReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeterIngestorService_SubmitReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeterIngestorServiceServer).SubmitReading(ctx, req.(*MeterReading))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeterIngestorService_SubmitBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMeterReadings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeterIngestorServiceServer).SubmitBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeterIngestorService_SubmitBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeterIngestorServiceServer).SubmitBatch(ctx, req.(*BatchMeterReadings))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeterIngestorService_StreamReadings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MeterIngestorServiceServer).StreamReadings(&grpc.GenericServerStream[MeterReading, BatchMeterReadingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeterIngestorService_StreamReadingsServer = grpc.ClientStreamingServer[MeterReading, BatchMeterReadingResponse]

func _MeterIngestorService_GetLatestReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeterIngestorServiceServer).GetLatestReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeterIngestorService_GetLatestReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeterIngestorServiceServer).GetLatestReading(ctx, req.(*GetLatestReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeterIngestorService_GetReadingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeterIngestorServiceServer).GetReadingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeterIngestorService_GetReadingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeterIngestorServiceServer).GetReadingHistory(ctx, req.(*GetReadingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeterIngestorService_ServiceDesc is the grpc.ServiceDesc for MeterIngestorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeterIngestorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meter.MeterIngestorService",
	HandlerType: (*MeterIngestorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitReading",
			Handler:    _MeterIngestorService_SubmitReading_Handler,
		},
		{
			MethodName: "SubmitBatch",
			Handler:    _MeterIngestorService_SubmitBatch_Handler,
		},
		{
			MethodName: "GetLatestReading",
			Handler:    _MeterIngestorService_GetLatestReading_Handler,
		},
		{
			MethodName: "GetReadingHistory",
			Handler:    _MeterIngestorService_GetReadingHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReadings",
			Handler:       _MeterIngestorService_StreamReadings_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "meter.proto",
}
