// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: meter.proto

package meter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeterReading struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                           // Physical meter serial / IoT device ID
	GwlAccountNumber string                 `protobuf:"bytes,2,opt,name=gwl_account_number,json=gwlAccountNumber,proto3" json:"gwl_account_number,omitempty"` // GWL account number this meter belongs to
	ReadingM3        float64                `protobuf:"fixed64,3,opt,name=reading_m3,json=readingM3,proto3" json:"reading_m3,omitempty"`                      // Cumulative reading in cubic metres
	FlowRateM3H      float64                `protobuf:"fixed64,4,opt,name=flow_rate_m3h,json=flowRateM3h,proto3" json:"flow_rate_m3h,omitempty"`              // Instantaneous flow rate (m³/hr), 0 if not available
	PressureBar      float64                `protobuf:"fixed64,5,opt,name=pressure_bar,json=pressureBar,proto3" json:"pressure_bar,omitempty"`                // Line pressure in bar, 0 if not available
	ReadMethod       string                 `protobuf:"bytes,6,opt,name=read_method,json=readMethod,proto3" json:"read_method,omitempty"`                     // "AMR", "MANUAL", "GPRS", "NB_IOT"
	ReaderId         string                 `protobuf:"bytes,7,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`                           // Badge/device ID of reader (empty for AMR)
	ReadingTimestamp *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=reading_timestamp,json=readingTimestamp,proto3" json:"reading_timestamp,omitempty"`
	BatteryVoltage   float64                `protobuf:"fixed64,9,opt,name=battery_voltage,json=batteryVoltage,proto3" json:"battery_voltage,omitempty"`                                        // IoT device battery (V), 0 if N/A
	TamperDetected   bool                   `protobuf:"varint,10,opt,name=tamper_detected,json=tamperDetected,proto3" json:"tamper_detected,omitempty"`                                        // Tamper flag from smart meter
	DistrictCode     string                 `protobuf:"bytes,11,opt,name=district_code,json=districtCode,proto3" json:"district_code,omitempty"`                                               // District code for routing
	Metadata         map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Extensible key-value metadata
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeterReading) Reset() {
	*x = MeterReading{}
	mi := &file_meter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeterReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeterReading) ProtoMessage() {}

func (x *MeterReading) ProtoReflect() protoreflect.Message {
	mi := &file_meter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeterReading.ProtoReflect.Descriptor instead.
func (*MeterReading) Descriptor() ([]byte, []int) {
	return file_meter_proto_rawDescGZIP(), []int{0}
}

func (x *MeterReading) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *MeterReading) GetGwlAccountNumber() string {
	if x != nil {
		return x.GwlAccountNumber
	}
	return ""
}

func (x *MeterReading) GetReadingM3() float64 {
	if x != nil {
		return x.ReadingM3
	}
	return 0
}

func (x *MeterReading) GetFlowRateM3H() float64 {
	if x != nil {
		return x.FlowRateM3H
	}
	return 0
}

func (x *MeterReading) GetPressureBar() float64 {
	if x != nil {
		return x.PressureBar
	}
	return 0
}

func (x *MeterReading) GetReadMethod() string {
	if x != nil {
		return x.ReadMethod
	}
	return ""
}

func (x *MeterReading) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

func (x *MeterReading) GetReadingTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadingTimestamp
	}
	return nil
}

func (x *MeterReading) GetBatteryVoltage() float64 {
	if x != nil {
		return x.BatteryVoltage
	}
	return 0
}

func (x *MeterReading) GetTamperDetected() bool {
	if x != nil {
		return x.TamperDetected
	}
	return false
}

func (x *MeterReading) GetDistrictCode() string {
	if x != nil {
		return x.DistrictCode
	}
	return ""
}

func (x *MeterReading) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MeterReadingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ReadingId      string                 `protobuf:"bytes,2,opt,name=reading_id,json=readingId,proto3" json:"reading_id,omitempty"` // UUID assigned to this reading
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	AnomalyFlagged bool                   `protobuf:"varint,4,opt,name=anomaly_flagged,json=anomalyFlagged,proto3" json:"anomaly_flagged,omitempty"` // True if sentinel pre-check flagged this reading
	AnomalyReason  string                 `protobuf:"bytes,5,opt,name=anomaly_reason,json=anomalyReason,proto3" json:"anomaly_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MeterReadingResponse) Reset() {
	*x = MeterReadingResponse{}
	mi := &file_meter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeterReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeterReadingResponse) ProtoMessage() {}

func (x *MeterReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeterReadingResponse.ProtoReflect.Descriptor instead.
func (*MeterReadingResponse) Descriptor() ([]byte, []int) {
	return file_meter_proto_rawDescGZIP(), []int{1}
}

func (x *MeterReadingResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *MeterReadingResponse) GetReadingId() string {
	if x != nil {
		return x.ReadingId
	}
	return ""
}

func (x *MeterReadingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MeterReadingResponse) GetAnomalyFlagged() bool {
	if x != nil {
		return x.AnomalyFlagged
	}
	return false
}

func (x *MeterReadingResponse) GetAnomalyReason() string {
	if x != nil {
		return x.AnomalyReason
	}
	return ""
}

type BatchMeterReadings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*MeterReading        `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	SourceSystem  string                 `protobuf:"bytes,2,opt,name=source_system,json=sourceSystem,proto3" json:"source_system,omitempty"` // "AMR_GATEWAY", "FIELD_APP", "MANUAL_UPLOAD"
	BatchId       string                 `protobuf:"bytes,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`                // Idempotency key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMeterReadings) Reset() {
	*x = BatchMeterReadings{}
	mi := &file_meter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMeterReadings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMeterReadings) ProtoMessage() {}

func (x *BatchMeterReadings) ProtoReflect() protoreflect.Message {
	mi := &file_meter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMeterReadings.ProtoReflect.Descriptor instead.
func (*BatchMeterReadings) Descriptor() ([]byte, []int) {
	return file_meter_proto_rawDescGZIP(), []int{2}
}

func (x *BatchMeterReadings) GetReadings() []*MeterReading {
	if x != nil {
		return x.Readings
	}
	return nil
}

func (x *BatchMeterReadings) GetSourceSystem() string {
	if x != nil {
		return x.SourceSystem
	}
	return ""
}

func (x *BatchMeterReadings) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type BatchMeterReadingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected       int32                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	AnomalyFlagged int32                  `protobuf:"varint,3,opt,name=anomaly_flagged,json=anomalyFlagged,proto3" json:"anomaly_flagged,omitempty"`
	Errors         []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	BatchId        string                 `protobuf:"bytes,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchMeterReadingResponse) Reset() {
	*x = BatchMeterReadingResponse{}
	mi := &file_meter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMeterReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMeterReadingResponse) ProtoMessage() {}

func (x *BatchMeterReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMeterReadingResponse.ProtoReflect.Descriptor instead.
func (*BatchMeterReadingResponse) Descriptor() ([]byte, []int) {
	return file_meter_proto_rawDescGZIP(), []int{3}
}

func (x *BatchMeterReadingResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *BatchMeterReadingResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *BatchMeterReadingResponse) GetAnomalyFlagged() int32 {
	if x != nil {
		return x.AnomalyFlagged
	}
	return 0
}

func (x *BatchMeterReadingResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BatchMeterReadingResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type GetLatestReadingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GwlAccountNumber string                 `protobuf:"bytes,1,opt,name=gwl_account_number,json=gwlAccountNumber,proto3" json:"gwl_account_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetLatestReadingRequest) Reset() {
	*x = GetLatestReadingRequest{}
	mi := &file_meter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestReadingRequest) ProtoMessage() {}

func (x *GetLatestReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestReadingRequest.ProtoReflect.Descriptor instead.
func (*GetLatestReadingRequest) Descriptor() ([]byte, []int) {
	return file_meter_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestReadingRequest) GetGwlAccountNumber() string {
	if x != nil {
		return x.GwlAccountNumber
	}
	return ""
}

type GetReadingHistoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GwlAccountNumber string                 `protobuf:"bytes,1,opt,name=gwl_account_number,json=gwlAccountNumber,proto3" json:"gwl_account_number,omitempty"`
	From             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To               *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Limit            int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetReadingHistoryRequest) Reset() {
	*x = GetReadingHistoryRequest{}
	mi := &file_meter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingHistoryRequest) ProtoMessage() {}

func (x *GetReadingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetReadingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_meter_proto_rawDescGZIP(), []int{5}
}

func (x *GetReadingHistoryRequest) GetGwlAccountNumber() string {
	if x != nil {
		return x.GwlAccountNumber
	}
	return ""
}

func (x *GetReadingHistoryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetReadingHistoryRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetReadingHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*MeterReading        `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadingHistoryResponse) Reset() {
	*x = ReadingHistoryResponse{}
	mi := &file_meter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingHistoryResponse) ProtoMessage() {}

func (x *ReadingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingHistoryResponse.ProtoReflect.Descriptor instead.
func (*ReadingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_meter_proto_rawDescGZIP(), []int{6}
}

func (x *ReadingHistoryResponse) GetReadings() []*MeterReading {
	if x != nil {
		return x.Readings
	}
	return nil
}

func (x *ReadingHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_meter_proto protoreflect.FileDescriptor

const file_meter_proto_rawDesc = "" +
	"\n" +
	"\vmeter.proto\x12\x05meter\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x04\n" +
	"\fMeterReading\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12,\n" +
	"\x12gwl_account_number\x18\x02 \x01(\tR\x10gwlAccountNumber\x12\x1d\n" +
	"\n" +
	"reading_m3\x18\x03 \x01(\x01R\treadingM3\x12\"\n" +
	"\rflow_rate_m3h\x18\x04 \x01(\x01R\vflowRateM3h\x12!\n" +
	"\fpressure_bar\x18\x05 \x01(\x01R\vpressureBar\x12\x1f\n" +
	"\vread_method\x18\x06 \x01(\tR\n" +
	"readMethod\x12\x1b\n" +
	"\treader_id\x18\a \x01(\tR\breaderId\x12G\n" +
	"\x11reading_timestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10readingTimestamp\x12'\n" +
	"\x0fbattery_voltage\x18\t \x01(\x01R\x0ebatteryVoltage\x12'\n" +
	"\x0ftamper_detected\x18\n" +
	" \x01(\bR\x0etamperDetected\x12#\n" +
	"\rdistrict_code\x18\v \x01(\tR\fdistrictCode\x12=\n" +
	"\bmetadata\x18\f \x03(\v2!.meter.MeterReading.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x14MeterReadingResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"reading_id\x18\x02 \x01(\tR\treadingId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12'\n" +
	"\x0fanomaly_flagged\x18\x04 \x01(\bR\x0eanomalyFlagged\x12%\n" +
	"\x0eanomaly_reason\x18\x05 \x01(\tR\ranomalyReason\"\x85\x01\n" +
	"\x12BatchMeterReadings\x12/\n" +
	"\breadings\x18\x01 \x03(\v2\x13.meter.MeterReadingR\breadings\x12#\n" +
	"\rsource_system\x18\x02 \x01(\tR\fsourceSystem\x12\x19\n" +
	"\bbatch_id\x18\x03 \x01(\tR\abatchId\"\xaf\x01\n" +
	"\x19BatchMeterReadingResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x05R\brejected\x12'\n" +
	"\x0fanomaly_flagged\x18\x03 \x01(\x05R\x0eanomalyFlagged\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\tR\abatchId\"G\n" +
	"\x17GetLatestReadingRequest\x12,\n" +
	"\x12gwl_account_number\x18\x01 \x01(\tR\x10gwlAccountNumber\"\xba\x01\n" +
	"\x18GetReadingHistoryRequest\x12,\n" +
	"\x12gwl_account_number\x18\x01 \x01(\tR\x10gwlAccountNumber\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"_\n" +
	"\x16ReadingHistoryResponse\x12/\n" +
	"\breadings\x18\x01 \x03(\v2\x13.meter.MeterReadingR\breadings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x8e\x03\n" +
	"\x14MeterIngestorService\x12A\n" +
	"\rSubmitReading\x12\x13.meter.MeterReading\x1a\x1b.meter.MeterReadingResponse\x12J\n" +
	"\vSubmitBatch\x12\x19.meter.BatchMeterReadings\x1a .meter.BatchMeterReadingResponse\x12I\n" +
	"\x0eStreamReadings\x12\x13.meter.MeterReading\x1a .meter.BatchMeterReadingResponse(\x01\x12G\n" +
	"\x10GetLatestReading\x12\x1e.meter.GetLatestReadingRequest\x1a\x13.meter.MeterReading\x12S\n" +
	"\x11GetReadingHistory\x12\x1f.meter.GetReadingHistoryRequest\x1a\x1d.meter.ReadingHistoryResponseBAZ?github.com/ArowuTest/gn-waas/backend/meter-ingestor/proto/meterb\x06proto3"

var (
	file_meter_proto_rawDescOnce sync.Once
	file_meter_proto_rawDescData []byte
)

func file_meter_proto_rawDescGZIP() []byte {
	file_meter_proto_rawDescOnce.Do(func() {
		file_meter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meter_proto_rawDesc), len(file_meter_proto_rawDesc)))
	})
	return file_meter_proto_rawDescData
}

var file_meter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_meter_proto_goTypes = []any{
	(*MeterReading)(nil),              // 0: meter.MeterReading
	(*MeterReadingResponse)(nil),      // 1: meter.MeterReadingResponse
	(*BatchMeterReadings)(nil),        // 2: meter.BatchMeterReadings
	(*BatchMeterReadingResponse)(nil), // 3: meter.BatchMeterReadingResponse
	(*GetLatestReadingRequest)(nil),   // 4: meter.GetLatestReadingRequest
	(*GetReadingHistoryRequest)(nil),  // 5: meter.GetReadingHistoryRequest
	(*ReadingHistoryResponse)(nil),    // 6: meter.ReadingHistoryResponse
	nil,                               // 7: meter.MeterReading.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_meter_proto_depIdxs = []int32{
	8,  // 0: meter.MeterReading.reading_timestamp:type_name -> google.protobuf.Timestamp
	7,  // 1: meter.MeterReading.metadata:type_name -> meter.MeterReading.MetadataEntry
	0,  // 2: meter.BatchMeterReadings.readings:type_name -> meter.MeterReading
	8,  // 3: meter.GetReadingHistoryRequest.from:type_name -> google.protobuf.Timestamp
	8,  // 4: meter.GetReadingHistoryRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 5: meter.ReadingHistoryResponse.readings:type_name -> meter.MeterReading
	0,  // 6: meter.MeterIngestorService.SubmitReading:input_type -> meter.MeterReading
	2,  // 7: meter.MeterIngestorService.SubmitBatch:input_type -> meter.BatchMeterReadings
	0,  // 8: meter.MeterIngestorService.StreamReadings:input_type -> meter.MeterReading
	4,  // 9: meter.MeterIngestorService.GetLatestReading:input_type -> meter.GetLatestReadingRequest
	5,  // 10: meter.MeterIngestorService.GetReadingHistory:input_type -> meter.GetReadingHistoryRequest
	1,  // 11: meter.MeterIngestorService.SubmitReading:output_type -> meter.MeterReadingResponse
	3,  // 12: meter.MeterIngestorService.SubmitBatch:output_type -> meter.BatchMeterReadingResponse
	3,  // 13: meter.MeterIngestorService.StreamReadings:output_type -> meter.BatchMeterReadingResponse
	0,  // 14: meter.MeterIngestorService.GetLatestReading:output_type -> meter.MeterReading
	6,  // 15: meter.MeterIngestorService.GetReadingHistory:output_type -> meter.ReadingHistoryResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_meter_proto_init() }
func file_meter_proto_init() {
	if File_meter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meter_proto_rawDesc), len(file_meter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meter_proto_goTypes,
		DependencyIndexes: file_meter_proto_depIdxs,
		MessageInfos:      file_meter_proto_msgTypes,
	}.Build()
	File_meter_proto = out.File
	file_meter_proto_goTypes = nil
	file_meter_proto_depIdxs = nil
}
