-- ============================================================
-- Migration 026: RLS Defence-in-Depth for Billing Tables
-- ============================================================
-- Adds Row-Level Security policies to three billing-related
-- tables that were missing RLS coverage (RLS-M01):
--
--   • gwl_bills          — GWL billing records (no district_id;
--                          district is derived via account_id →
--                          water_accounts.district_id)
--   • shadow_bills       — GN-WAAS shadow bill calculations (same
--                          indirect district relationship via account_id)
--   • gwl_monthly_reports — Monthly district summary reports
--                          (has district_id directly; NULL = national)
--
-- For gwl_bills and shadow_bills the policy uses a subquery on
-- water_accounts (which already has RLS) to derive the district.
-- This is defence-in-depth: the api-gateway already JOINs
-- water_accounts on every user-facing query, but adding RLS at
-- the table level prevents any direct query from leaking
-- cross-district data.
--
-- For gwl_monthly_reports, district_id is nullable (NULL = national
-- summary). National summaries are visible to admins only; district
-- rows are visible to the matching district user.
--
-- Pattern mirrors migration 012 (existing RLS tables):
--   FORCE ROW LEVEL SECURITY
--   FOR ALL TO gnwaas_app
--   USING (current_user_is_admin() OR ...)
--
-- All policies are idempotent: DROP POLICY IF EXISTS precedes each
-- CREATE POLICY (follows the pattern in migrations 024 and 025).
--
-- Helper functions used (defined in migration 012):
--   current_user_is_admin()  → TRUE for SUPER_ADMIN / SYSTEM_ADMIN / MOF_AUDITOR
--   current_district_id()    → UUID from SET LOCAL app.district_id
-- ============================================================

-- ─── gwl_bills ───────────────────────────────────────────────────────────────
-- GWL billing records mirrored from ERP via CDC.
-- No district_id column; district is derived via account_id → water_accounts.
ALTER TABLE gwl_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE gwl_bills FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rls_gwl_bills_district ON gwl_bills;
CREATE POLICY rls_gwl_bills_district ON gwl_bills
    FOR ALL TO gnwaas_app
    USING (
        current_user_is_admin()
        OR account_id IN (
            SELECT id FROM water_accounts
            WHERE district_id = current_district_id()
        )
    );

-- ─── shadow_bills ────────────────────────────────────────────────────────────
-- GN-WAAS shadow bill calculations (PURC tariff recalculation).
-- No district_id column; district is derived via account_id → water_accounts.
ALTER TABLE shadow_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE shadow_bills FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rls_shadow_bills_district ON shadow_bills;
CREATE POLICY rls_shadow_bills_district ON shadow_bills
    FOR ALL TO gnwaas_app
    USING (
        current_user_is_admin()
        OR account_id IN (
            SELECT id FROM water_accounts
            WHERE district_id = current_district_id()
        )
    );

-- ─── gwl_monthly_reports ─────────────────────────────────────────────────────
-- Monthly district summary reports generated by the GWL case workflow.
-- district_id is nullable: NULL = national summary (admin-only).
ALTER TABLE gwl_monthly_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE gwl_monthly_reports FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rls_gwl_monthly_reports_district ON gwl_monthly_reports;
CREATE POLICY rls_gwl_monthly_reports_district ON gwl_monthly_reports
    FOR ALL TO gnwaas_app
    USING (
        current_user_is_admin()
        OR (district_id IS NOT NULL AND district_id = current_district_id())
    );
